### ISSUE TITLE
 files downloaded with curl are corrupted because of  `.curlrc`

### ISSUE THREAD

**Issue by niamotullah** [sebastienrousseau/dotfiles#54]
**Describe the bug**
This issue is reported  [here](https://github.com/curl/curl/issues/13094)
Please fix this

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS
- Browser
- Version

**Smartphone (please complete the following information):**

- Device
- OS
- Browser
- Version

**Additional context**

**Comment by piru** [comment]
This issue is caused by `--include` here https://github.com/sebastienrousseau/dotfiles/blob/82d4d8d739b0da793fbffa407c7ea6fe13f1343e/lib/configurations/curl/curlrc#L24

This will make curl include the HTTP headers in the output. Generally this is NOT what you want.

More generally I would shy away from changing the curl defaults like this. This is asking for a lot of trouble when scripts and other curl usage get thrown off by the wildly non-standard defaults.
